### ISSUE TITLE
[NOT AN ISSUE] Hi i don't know how to contact you but i need to talk to you

### ISSUE THREAD

**Issue by ToufouMaster** [synap5e/pydetours#1]
Hi i know this is not an real issue so i will delete it in a week

I need to speek with you about an old project you made for CubeWorld
you maked a FastTravel mod and i send you an Email for Help

I'm searching how i can make a Alpha Version Mod if you agree can you answer me with a mail at owen.kala@gmx.fr or on discord with 2 AZ ToufouMaster#6349 Thanks

**Comment by synap5e** [comment]
Responded.

Incidentally this project should be suitable for modding cubeworld to achieve the same things my fast travel mod did, but in a much easier manner.
